# Generated by Django 4.1.3 on 2022-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('org_id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_arr', models.CharField(max_length=1000)),
            ],
        ),
    ]
