# Generated by Django 4.1.3 on 2022-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkyu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AminoVector',
            fields=[
                ('amino_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
