# Generated by Django 4.1.3 on 2022-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkyu', '0002_aminovector'),
    ]

    operations = [
        migrations.AddField(
            model_name='aminovector',
            name='amino_name',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aminovector',
            name='amino_x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aminovector',
            name='amino_y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aminovector',
            name='amino_z',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
