# Generated by Django 4.1.3 on 2022-12-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenkyu', '0003_aminovector_amino_name_aminovector_amino_x_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AminoVector',
        ),
    ]
