# Generated by Django 4.1.3 on 2022-12-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkyu', '0004_delete_aminovector'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='org_check',
            field=models.BooleanField(default=True),
        ),
    ]
