# Generated by Django 4.1.3 on 2022-12-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenkyu', '0005_organism_org_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='org_check',
        ),
    ]
